### ISSUE TITLE
Conflict with Pin Cushion

### ISSUE THREAD

**Issue by nschoenwald** [MrPrimate/NoteLicker#1]
**Describe the bug**
I wanted to try out the module, but it looks like there is a conflict with Pin Cushion. Is this something that could be resolved? I need the pin cushion functionality of always showing notes.

![image](https://github.com/MrPrimate/NoteLicker/assets/72390280/dcce3e79-c671-4cec-a45d-3577defdfb5e)

**Environment:**
Chrome, current versions of foundry and dnd5e.

**Comment by MrPrimate** [comment]
Resolved in v0.1.1
