### ISSUE TITLE
"Disable auto icon generation" is missing

### ISSUE THREAD

**Issue by DoggieBert** [MrPrimate/NoteLicker#2]
**Describe the bug**
There is no "Disable auto icon generation" checkbox in the note configuration menu.

**To Reproduce**
1. Place a map note
2. Open up the note configuration menu
3. There is no checkbox for "Disable auto icon generation"

**Expected behavior**
There should be a "Disable auto icon generation" checkbox in the note configuration menu

**Screenshots**

**Environment:**
 - Browser - Chrome
 - Foundry Version - 11.305
 - Pathfinder System Version - 5.1.2
 - Module Version - 0.1.2
 - Does this behaviour occur with other modules disabled: Yes, empty world with all other modules (except libWrapper) disabled

**Comment by MrPrimate** [comment]
Whoops! Thanks for the report. Fixed in v0.1.3
