### ISSUE TITLE
Notelicker Changes It's Mind - Note Number from Page Title (section number getting injected)

### ISSUE THREAD

**Issue by kiloforce** [MrPrimate/NoteLicker#5]
**Describe the bug**
If I have a page title that starts with a number, Note Licker creates a Note with an icon with that number, but then decides against it and goes with the section number instead.  Could it instead default to the page number for the Text Label as it seemed to have initially been correctly done?

**To Reproduce**
1. Create journal entry with title starting with number
2. Drag and drop page to canvas.  It creates note with number matching page title
3. Click "Update Map Note".  It changes the note to instead match the page section instead.

**Expected behavior**
If the page title starts with a number, could Note Licker drop the section from the "Text Label".  I would actually prefer it if the default Foundry sections were never included.

**Screenshots**

Before:
![image](https://github.com/MrPrimate/NoteLicker/assets/433058/10bb4b6f-bfd0-4c01-9ec6-f5425a502de7)

After:
![image](https://github.com/MrPrimate/NoteLicker/assets/433058/51ec7bbd-7300-4095-a858-43eb12d16bd7)

**Environment:**
 - Browser: Chrome
 - Foundry Version: 11 v315
 - DnD Version: 2.4.1
 - Module Version: 0.1.4

**Comment by kiloforce** [comment]
Umm... well.. so funny story...  I did some digging, and it turns out this issue is actually caused by some other module, so I guess you don't need to worry about it (_hold for the punchline_).  I disabled that other module and the issue went away.

I don't know how on earth the other module would cause the above symptom, but the injection of the section numbers is somehow coming from what I would consider a completely unrelated module that shouldn't even be active, as I am not doing any sort of importing at the moment?  I may now have to rethink even my "minimal" FoundryVTT testing environment.  Anyway, if you would like to investigate that other module, from that other one person:   ;-)

MrPrimate/ddb-importer  (v3.7.13)

Yeah, I am as shocked as you are.  I thought it was about as unintrustive as a module could be, and only activated on demand?

**Comment by MrPrimate** [comment]
NoteLicker is born out of functionality that was created in ddb-importer for adventure imports - I'll see what the conflict is!

**Comment by MrPrimate** [comment]
Fixed, in v3.7.14, out in a couple of days, if you can check to make sure it works for you, that would be grand!

**Comment by kiloforce** [comment]
When it is available, I certainly will try it, thanks.
