### ISSUE TITLE
Use 'requiresReload' instead of `debounceReload`

### ISSUE THREAD

**Issue by farling42** [MrPrimate/NoteLicker#6]
Currently almost as soon as one of this module's settings is changed then Foundry reloads (which takes a time with any PF2 game). It would be preferable to wait until the "save settings" button is pressed in the module settings window.

Foundry provides the `requiresReload` boolean standard flag for game settings, which would make it far less annoying when changing multiple settings.

**Comment by MrPrimate** [comment]
I have no idea why this isn't set as requires reload - I think maybe an artifact of my first pass pre-release. I'll get this changed.

**Comment by MrPrimate** [comment]
In v0.1.8
